[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { workspace = true }
anyhow = { workspace = true }
rustc-hash = { workspace = true }
lz4_flex = { workspace = true }
